basePath: /v1
definitions:
  handler.ReqUserLogin:
    properties:
      password:
        maxLength: 32
        minLength: 5
        type: string
      username:
        maxLength: 32
        minLength: 5
        type: string
    type: object
  handler.RspUserLogin:
    properties:
      token:
        type: string
    type: object
host: 47.114.74.103:20000
info:
  contact:
    email: wukong@pplabs.org
    name: wukong
  description: The pi-cloud-monitor RESTful API Documents.
  license: {}
  title: pi-cloud-monitor RESTful API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户名和密码
        in: body
        name: ReqUserLogin
        required: true
        schema:
          $ref: '#/definitions/handler.ReqUserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RspUserLogin'
        "401":
          description: 用户名或密码错误
        "500":
          description: 内部错误
      summary: 用户登录
      tags:
      - 用户
swagger: "2.0"
